language: C++
addons:
  apt:
    packages:
    - cmake
    - python3
install:
  - pip3 install --upgrade pip
  - pip3 install conan
  - conan remote add $CONAN_REMOTE_USERNAME $CONAN_REMOTE_URL
script: 
  - conan create . jabaa/stable -tf .
  - conan create . jabaa/stable -tf . -o shared=False
compiler:
  - clang
  - gcc
