dist: trusty
sudo: false

language: C++
env:
  global:
    - VERSION=0.1
  matrix:
    - SHARED=True
    - SHARED=False
addons:
  apt:
    update: true
    packages:
    - cmake
    - python3
    - python3-pip
install:
  - pip3 install --user pip
  - pip3 install --user setuptools
  - pip3 install --user conan
  - conan remote add $CONAN_REMOTE_NAME $CONAN_REMOTE_URL
  - conan user -r $CONAN_REMOTE_NAME -p $CONAN_REMOTE_PASSWORD $CONAN_REMOTE_USERNAME
script:
  - conan create . jabaa/stable -tf . -o shared=$SHARED && conan upload -r $CONAN_REMOTE_USERNAME --all ThreadPool/$VERSION@$CONAN_REMOTE_USERNAME/stable
compiler:
  - clang
  - gcc
